name: C/C++ CI

on:
  push:
    branches: [ "main", "project" ]
  pull_request:
    branches: [ "main", "project" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Checkout project branch
      run: |
        git checkout project
        
    - name: Configure
      run: |
        cd new_project
        ./configure
        
    - name: Build
      run: |
        cd new_project
        make
        
    - name: Test
      run: |
        cd new_project
        make check
        
    - name: Package
      run: |
        cd new_project
        make distcheck
